#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# colab_run.sh — Start the Hunyuan3D 2.1 API server inside Colab.
#
# Sources the .colab.env generated by colab_setup.sh, launches uvicorn
# in the background, and waits for /health to return 200.
#
# Usage:
#   !bash /content/hunyuan3d-api/scripts/colab_run.sh &
# ---------------------------------------------------------------------------
set -euo pipefail

SERVICE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${SERVICE_ROOT}/.colab.env"
LOG="${SERVICE_ROOT}/outputs/server.log"
PORT="${HY3D_PORT:-8080}"
MAX_WAIT="${MAX_WAIT:-300}"

info()  { printf "\033[1;34m== %s\033[0m\n" "$*"; }
warn()  { printf "\033[1;33m** %s\033[0m\n" "$*"; }
error() { printf "\033[1;31m!! %s\033[0m\n" "$*" >&2; exit 1; }

# ── source env ───────────────────────────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
    info "Sourcing $ENV_FILE"
    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a
else
    warn "$ENV_FILE not found; using current env vars"
fi

# ── kill any running instance ────────────────────────────────────────────
OLD_PID=$(pgrep -f "app.server" 2>/dev/null || true)
if [ -n "$OLD_PID" ]; then
    warn "Stopping old server (PID=$OLD_PID)"
    kill "$OLD_PID" 2>/dev/null || true
    sleep 2
fi

mkdir -p "${SERVICE_ROOT}/outputs"

# ── launch ───────────────────────────────────────────────────────────────
info "Starting uvicorn on port $PORT (logs → $LOG)"
cd "$SERVICE_ROOT"
nohup python -m app.server > "$LOG" 2>&1 &
SERVER_PID=$!
echo "$SERVER_PID" > "${SERVICE_ROOT}/outputs/server.pid"
info "Server PID: $SERVER_PID"

# ── wait for health ──────────────────────────────────────────────────────
info "Waiting for /health (max ${MAX_WAIT}s) ..."
ELAPSED=0
while [ $ELAPSED -lt $MAX_WAIT ]; do
    if curl -sf "http://127.0.0.1:${PORT}/health" >/dev/null 2>&1; then
        info "Server healthy after ${ELAPSED}s"
        curl -s "http://127.0.0.1:${PORT}/health" | python -m json.tool 2>/dev/null || true
        exit 0
    fi
    sleep 2
    ELAPSED=$((ELAPSED + 2))
done

error "Server did not become healthy within ${MAX_WAIT}s.  Check: $LOG"
